#!/usr/bin/env python3
"""Cosense が同梱している app.css から、プロジェクトテーマごとの CSS 変数を
取り出し、theme.rs で使う Rust の match 群を stdout に出す。

    scripts/cosense-theme-vars.py [app.css のパス]

パスを省略すると https://scrapbox.io/assets/css/app.css を取得する。
web 側が変わったら再生成して diff を取る(2026-09-06 実測が基準)。
出すのは次の2テーブル:

- `--navbar-bg`   → ヘッダ fg/bg(theme.rs::cosense_navbar_rgba)
- `--page-link-color` + `--empty-page-link-color`
                  → 本文リンク色(theme.rs::cosense_link_colors)
- `--telomere-unread` + `--telomere-updated`
                  → テロメアの未読・ロード後更新色(theme.rs::cosense_telomere_tint)

テーマが自前で定義しない変数は web では `var(--x, FALLBACK)` の基底に落ちる
ので、それも拾って全テーマで値を持つ。テロメアは **2世代ある**:新系
(blue/green/orange/purple/red/paper 系)は青 `#89a3ff`/`#6b8cff`、旧系
(hacker2/lgreen/mred/summer)は緑 `#7fca8f`/`#47ba5f` を自前で定義する。
定義しないテーマは css のフォールバック(青系)に落ちる。既読は端末側の
罫線グレーに任せるので、取り出さない。
"""

import re
import sys
import urllib.request

URL = "https://scrapbox.io/assets/css/app.css"


def fetch(path=None):
    if path:
        with open(path) as f:
            return f.read()
    return urllib.request.urlopen(URL).read().decode()


def blocks(css):
    """`html[data-project-theme=…]{…}` を波括弧対応で切り出す。"""
    out = {}
    for m in re.finditer(r"html\[data-project-theme=([a-z0-9-]+)\]\{", css):
        i = j = m.end()
        depth = 1
        while depth and j < len(css):
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
            j += 1
        out[m.group(1)] = css[i : j - 1]
    return out


def css_color(v):
    """hex / rgba() / hsl() を (r, g, b, alpha*255) に。分からなければ None。"""
    v = (v or "").strip()

    def h2(h):
        h = h.lstrip("#")
        if len(h) == 3:
            h = "".join(c * 2 for c in h)
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

    m = re.match(r"#([0-9a-fA-F]{3,6})$", v)
    if m:
        r, g, b = h2(m.group(1))
        return r, g, b, 255
    m = re.match(r"rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)", v)
    if m:
        r, g, b = (int(m.group(i)) for i in (1, 2, 3))
        a = float(m.group(4)) if m.group(4) else 1.0
        return r, g, b, int(a * 255 + 0.5)
    m = re.match(r"hsl\((\d+)(?:deg)?\s+([\d.]+)%\s+([\d.]+)%\s*(?:/\s*([\d.]+))?\)", v)
    if m:
        h, s, l = int(m.group(1)), float(m.group(2)) / 100, float(m.group(3)) / 100
        a = float(m.group(4)) if m.group(4) else 1.0
        if a > 1:  # `70%` が 70 と読めた
            a /= 100
        c = (1 - abs(2 * l - 1)) * s
        hp = (h % 360) / 60
        x = c * (1 - abs(hp % 2 - 1))
        rgb = [(c, x, 0), (x, c, 0), (0, c, x), (0, x, c), (x, 0, c), (c, 0, x)][int(hp)]
        m2 = l - c / 2
        r, g, b = (int((v2 + m2) * 255 + 0.5) for v2 in rgb)
        return r, g, b, int(a * 255 + 0.5)
    return None


def var_in(body, var):
    m = re.search(re.escape(var) + r":\s*([^;}]+)", body)
    return m.group(1).strip() if m else None


def fallback(css, var):
    """`var(--x, FALLBACK)` の FALLBACK。テーマが定義しない変数の基底値。"""
    m = re.search(re.escape(var) + r",\s*([^)]+)\)", css)
    return m.group(1).strip() if m else None


def main():
    css = fetch(sys.argv[1] if len(sys.argv) > 1 else None)
    bs = blocks(css)
    base_link = css_color(fallback(css, "--page-link-color"))
    base_empty = css_color(fallback(css, "--empty-page-link-color"))
    print("// Generated by scripts/cosense-theme-vars.py from")
    print(f"// {URL} — measured values; regenerate when the web side changes.")
    print("let navbar = |t: &str| Option<(u8, u8, u8, u8)> { match t {")
    for n in sorted(bs):
        c = css_color(var_in(bs[n], "--navbar-bg"))
        if c:
            print(f'        "{n}" => Some(({c[0]}, {c[1]}, {c[2]}, {c[3]})),')
    print("        _ => None,\n    } };")
    print("let links = |t: &str| Option<(u8, u8, u8, u8, u8, u8)> { match t {")
    for n in sorted(bs):
        lk = css_color(var_in(bs[n], "--page-link-color")) or base_link
        ms = css_color(var_in(bs[n], "--empty-page-link-color")) or base_empty
        if lk and ms and lk[3] == 255 and ms[3] == 255:
            print(
                f'        "{n}" => Some(({lk[0]}, {lk[1]}, {lk[2]}, '
                f"{ms[0]}, {ms[1]}, {ms[2]})),"
            )
    print("        _ => None,\n    } };")
    base_ur = css_color(fallback(css, "--telomere-unread"))
    base_up = css_color(fallback(css, "--telomere-updated"))
    print("let telomere = |t: &str| Option<(u8, u8, u8, u8, u8, u8)> { match t {")
    for n in sorted(bs):
        ur = css_color(var_in(bs[n], "--telomere-unread")) or base_ur
        up = css_color(var_in(bs[n], "--telomere-updated")) or base_up
        if ur and up and ur[3] == 255 and up[3] == 255:
            print(
                f'        "{n}" => Some(({ur[0]}, {ur[1]}, {ur[2]}, '
                f"{up[0]}, {up[1]}, {up[2]})),"
            )
    print("        _ => None,\n    } };")
    print("// telomere css fallback:", base_ur, base_up)


if __name__ == "__main__":
    main()
